# Generated by Django 5.0 on 2023-12-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "lastname",
                    models.CharField(max_length=100, verbose_name="sobrenome"),
                ),
                ("contact", models.CharField(max_length=100, verbose_name="contato")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
