# Generated by Django 4.2.3 on 2023-12-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="contact",
            field=models.CharField(
                default=None, max_length=100, verbose_name="contato"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="lastname",
            field=models.CharField(
                default=None, max_length=100, verbose_name="sobrenome"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(default=None, max_length=100, verbose_name="nome"),
        ),
    ]
