# Generated by Django 5.0 on 2023-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0002_alter_academy_contact_alter_academy_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="vencimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
