# Generated by Django 5.0 on 2024-01-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0003_academy_vencimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="contact",
            field=models.CharField(
                default=None,
                help_text="número de contato",
                max_length=100,
                verbose_name="contato",
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="lastname",
            field=models.CharField(
                default=None,
                help_text="sobrenome",
                max_length=100,
                verbose_name="sobrenome",
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(
                default=None, help_text="nome", max_length=100, verbose_name="nome"
            ),
        ),
    ]
