# Generated by Django 5.0 on 2024-01-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0004_alter_academy_contact_alter_academy_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="contact",
            field=models.CharField(
                default=None, max_length=100, verbose_name="contato"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="lastname",
            field=models.CharField(
                default=None, max_length=100, verbose_name="sobrenome"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(default=None, max_length=100, verbose_name="nome"),
        ),
    ]
