# Generated by Django 5.0.2 on 2024-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0005_alter_academy_contact_alter_academy_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="contact",
            field=models.CharField(max_length=100, verbose_name="contato"),
        ),
        migrations.AlterField(
            model_name="academy",
            name="lastname",
            field=models.CharField(max_length=100, verbose_name="sobrenome"),
        ),
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nome"),
        ),
    ]
