# Generated by Django 5.0.2 on 2024-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0006_alter_academy_contact_alter_academy_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="vencimento",
            field=models.DateField(auto_now_add=True),
        ),
    ]
