# Generated by Django 5.0.2 on 2024-02-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0007_alter_academy_vencimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="vencimento",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
