# Generated by Django 5.0 on 2024-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0008_alter_academy_vencimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="cpf",
            field=models.CharField(
                default=14943651704, max_length=11, verbose_name="cpf"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="academy",
            name="contact",
            field=models.CharField(max_length=11, verbose_name="contato"),
        ),
    ]
