# Generated by Django 5.0 on 2024-03-04 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0009_academy_cpf_alter_academy_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="nome",
            ),
        ),
    ]
