# Generated by Django 5.0 on 2024-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0010_alter_academy_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nome"),
        ),
    ]
